icon:
  host: ${ORDS_HOST}
  hsr-service-url: ${HSR_SERVICE_URL}
  hsr-queue: ${HSR_QUEUE_NAME}
  ping-queue: ${PING_QUEUE_NAME}

spring:
  rabbitmq:
    host: ${RABBIT_MQ_HOST}
    username: ${RABBIT_MQ_USERNAME}
    password: ${RABBIT_MQ_PASSWORD}

server:
  port: 8085
