security:
  basic-auth:
    password: ${BASIC_AUTH_PASS}
    username: ${BASIC_AUTH_USER}
icon:
  host: http://127.0.0.1
  hsr-service-url: http://127.0.0.1
  hsr-queue: hsr-queue
  hsr-routing-key: HSR
  ping-queue: ping-queue
  ping-routing-key: PING
  exchange-name: EXCHANGE