##############################################################################################
#### Stage where the maven dependencies are cached                                         ###
##############################################################################################
FROM maven:3.8.3-openjdk-17 AS build

WORKDIR /app

COPY . .

RUN  mvn clean package \
     -P$jag-icon2-auth-application \
     -DskipTests=true

##############################################################################################
#### Stage where Docker is running a java process to run a service built in previous stage ###
##############################################################################################
FROM eclipse-temurin:17-jre-alpine

RUN apk update && apk upgrade --no-cache

COPY --from=build /app/jag-icon2-biometrics-application/target/jag-icon2-biometrics-application.jar /jag-icon2-biometrics-application.jar

ENTRYPOINT ["java", "-jar","/jag-icon2-biometrics-application.jar"]
