security:
  basic-auth:
    password: ${BASIC_AUTH_PASS}
    username: ${BASIC_AUTH_USER}
icon:
  host: https://127.0.0.1/
  username: ${BASIC_AUTH_USER}
  password: ${BASIC_AUTH_PASS}
  iis-host: https://127.0.0.1/
  ips-host: https://127.0.0.1/
  bsc-host: https://127.0.0.1/
  online-service-id: service-id

management:
  endpoints:
    web:
      exposure:
        include: metrics,prometheus,health