security:
  basic-auth:
    password: ${BASIC_AUTH_PASS}
    username: ${BASIC_AUTH_USER}
icon:
  ords-host: ${ORDS_HOST}
  iis-host: ${IIS_HOST}
  ips-host: ${IPS_HOST}
  bsc-host: ${BCS_HOST}
  online-service-id: ${ONLINE_SERVICE_ID}

management:
  endpoints:
    web:
      exposure:
        include: metrics,prometheus,health