apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: ${APP_NAME}
  description: Deployment template for the JAG-ICON2-COMMON-1-1

labels:
  app: ${APP_NAME}
  app.kubernetes.io/name: ${COMPONENT_NAME}
  app.kubernetes.io/part-of: ${APP_NAME}
  app.openshift.io/runtime: ${RUNTIME}

parameters:

  - name: APP_NAME
    description: The application name that each component is part of
    required: false
    value: jag-icon2

  - name: COMPONENT_NAME
    description: The application name that each component is part of
    required: false
    value: jag-icon2-common-1-1

  - name: OC_NAMESPACE
    description: The OpenShift namespace prefix
    required: false
    # Below value must be changed as per gold cluster oc nameplate
    value: af9914

  - name: OC_ENV
    description: The OpenShift environment, ie dev, test or prod
    required: true

  - name: RUNTIME
    description: The application name that each component is part of
    required: false
    value: java

  - name: DNS
    description: The application name that each component is part of
    required: false
    # Below value must be changed as per gold cluster certificate/DNS
    value: apps.gold.devops.gov.bc.ca

  - name: AUTH_HEADER
    description: The http Authorization header required for performing livenessProbe & readinessProbe in deployment config during container start.
    required: true
    value: ''

objects:

  ### JAG-ICON2-COMMON-1-1 Deployment Config ###
  - apiVersion: apps.openshift.io/v1
    kind: DeploymentConfig
    metadata:
      name: ${COMPONENT_NAME}
      namespace: ${OC_NAMESPACE}-${OC_ENV}

    spec:
      completionDeadlineSeconds: 1200
      replicas: 1
      selector:
        name: ${COMPONENT_NAME}
      strategy:
        type: Rolling
        maxSurge: 50%
        maxUnavailable: 0
      template:
        metadata:
          labels:
            name: ${COMPONENT_NAME}
        spec:
          containers:
            # Below Immage url must be changed as per gold cluster image stream
            - image: >-
                image-registry.openshift-image-registry.svc:5000/${OC_NAMESPACE}-tools/${COMPONENT_NAME}:${OC_ENV}
              name: ${COMPONENT_NAME}
              imagePullPolicy: Always
              ports:
                - containerPort: 8080
              env:
                - name: BASIC_AUTH_USER
                  valueFrom:
                    secretKeyRef:
                      name: jag-icon2-common-1-1-application-secrets
                      key: BASIC_AUTH_USER
                - name: BASIC_AUTH_PASS
                  valueFrom:
                    secretKeyRef:
                      name: jag-icon2-common-1-1-application-secrets
                      key: BASIC_AUTH_PASS
                - name: HSR_QUEUE_NAME
                  valueFrom:
                    secretKeyRef:
                      name: jag-icon2-common-1-1-application-secrets
                      key: HSR_QUEUE_NAME
                - name: HSR_ROUTING_KEY
                  valueFrom:
                    secretKeyRef:
                      name: jag-icon2-common-1-1-application-secrets
                      key: HSR_ROUTING_KEY
                - name: HSR_SERVICE_URL
                  valueFrom:
                    secretKeyRef:
                      name: jag-icon2-common-1-1-application-secrets
                      key: HSR_SERVICE_URL
                - name: ORDS_HOST
                  valueFrom:
                    secretKeyRef:
                      name: jag-icon2-common-1-1-application-secrets
                      key: ORDS_HOST
                - name: PING_QUEUE_NAME
                  valueFrom:
                    secretKeyRef:
                      name: jag-icon2-common-1-1-application-secrets
                      key: PING_QUEUE_NAME
                - name: PING_ROUTING_KEY
                  valueFrom:
                    secretKeyRef:
                      name: jag-icon2-common-1-1-application-secrets
                      key: PING_ROUTING_KEY
                - name: RABBIT_EXCHANGE_NAME
                  valueFrom:
                    secretKeyRef:
                      name: jag-icon2-common-1-1-application-secrets
                      key: RABBIT_EXCHANGE_NAME
                - name: RABBIT_MQ_HOST
                  valueFrom:
                    secretKeyRef:
                      name: jag-icon2-common-1-1-application-secrets
                      key: RABBIT_MQ_HOST
                - name: WS_AUTH_PASS
                  valueFrom:
                    secretKeyRef:
                      name: jag-icon2-common-1-1-application-secrets
                      key: WS_AUTH_PASS
                - name: WS_AUTH_USER
                  valueFrom:
                    secretKeyRef:
                      name: jag-icon2-common-1-1-application-secrets
                      key: WS_AUTH_USER
                - name: RABBIT_MQ_USERNAME
                  valueFrom:
                    secretKeyRef:
                      name: rabbitmq-cluster-secret
                      key: username
                - name: RABBIT_MQ_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: rabbitmq-cluster-secret
                      key: password
                - name: SPRING_PROFILES_ACTIVE
                  valueFrom:
                    secretKeyRef:
                      name: jag-icon2-splunk-config
                      key: SPRING_PROFILE
                - name: SPLUNK_HTTP_URL
                  valueFrom:
                    secretKeyRef:
                      name: jag-icon2-splunk-config
                      key: SPLUNK_HTTP_URL
                - name: SPLUNK_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: jag-icon2-splunk-config
                      key: SPLUNK_TOKEN
                - name: SPLUNK_INDEX
                  valueFrom:
                    secretKeyRef:
                      name: jag-icon2-splunk-config
                      key: SPLUNK_INDEX
              resources:
                limits:
                  cpu: 100m
                  memory: 200Mi
                requests:
                  cpu: 40m
                  memory: 100Mi
              livenessProbe:
                httpGet:
                  path: "/actuator/health"
                  port: 8080
                  scheme: HTTP
                  httpHeaders:
                    - name: Authorization
                      value: ${AUTH_HEADER}
                initialDelaySeconds: 100
                timeoutSeconds: 30
                periodSeconds: 10
                successThreshold: 1
                failureThreshold: 3
              readinessProbe:
                httpGet:
                  path: "/actuator/health"
                  port: 8080
                  scheme: HTTP
                  httpHeaders:
                    - name: Authorization
                      value: ${AUTH_HEADER}
                initialDelaySeconds: 100
                timeoutSeconds: 30
                periodSeconds: 10
                successThreshold: 1
                failureThreshold: 3
      triggers:
        - type: ConfigChange
        - type: ImageChange
          imageChangeParams:
            automatic: true
            containerNames:
              - ${COMPONENT_NAME}
            from:
              kind: ImageStreamTag
              namespace: ${OC_NAMESPACE}-tools
              name: ${COMPONENT_NAME}:${OC_ENV}
    status: {}

  ### JAG-ICON2-COMMON-1-1 Service ###
  - apiVersion: v1
    kind: Service
    metadata:
      name: ${COMPONENT_NAME}
      namespace: ${OC_NAMESPACE}-${OC_ENV}
    spec:
      ports:
        - name: http
          protocol: TCP
          port: 80
          targetPort: 8080
      selector:
        name: ${COMPONENT_NAME}
      sessionAffinity: None
      type: ClusterIP

  ### JAG-ICON2-COMMON-1-1 route ###
  - apiVersion: route.openshift.io/v1
    kind: Route
    metadata:
      name: ${COMPONENT_NAME}
      namespace: ${OC_NAMESPACE}-${OC_ENV}
    annotations:
      # if we do not use sticky-session, disable_cookies needs to be true
      haproxy.router.openshift.io/disable_cookies: "true"
      # balance algorithm
      haproxy.router.openshift.io/balance: roundrobin
    spec:
      host: ${COMPONENT_NAME}-${OC_NAMESPACE}-${OC_ENV}.${DNS}
      to:
        kind: Service
        name: ${COMPONENT_NAME}
        weight: 100
      port:
        targetPort: http
      tls:
        termination: edge
        insecureEdgeTerminationPolicy: None
      wildcardPolicy: None
