icon:
  host: http://127.0.0.1/
  username: ${BASIC_AUTH_USER}
  password: ${BASIC_AUTH_PASS}
  hsr-service-url: http://127.0.0.1/
  hsr-queue: hsr-queue
  ping-queue: ping-queue

spring:
  rabbitmq:
    host: redis
    port: 5672
