security:
  basic-auth:
    password: ${BASIC_AUTH_PASS}
    username: ${BASIC_AUTH_USER}
icon:
  host: http://127.0.0.1/
  username: ${BASIC_AUTH_USER}
  password: ${BASIC_AUTH_PASS}
management:
  endpoints:
    web:
      exposure:
        include: metrics,prometheus,health